### ISSUE TITLE
The program crashes

### ISSUE THREAD

**Issue by crismblog** [dglent/meteo-qt#70]
~ $meteo-qt
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/meteo_qt/meteo_qt.py", line 763, in run
    timeout=5)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <?xml version="1.0" encoding="UTF-8"?>
Aborted

**Comment by dglent** [comment]
It is first installation ?
Did you already configure any city ?

To see which url causes this open the ~/.config/meteo-qt/meteo-qt.conf and change the debug level from info to debug:

[Logging]
Level=DEBUG

Then send me the output of the terminal

**Comment by crismblog** [comment]
1. This is the second time I installed.

2. I do not use proxy.

3. I configured the city.

"***" represents API


`~ $meteo-qt
DEBUG: Update... - meteo_qt
DEBUG: Fetching url for actual weather: http://api.openweathermap.org/data/2.5/weather?id=664460&mode=xml&units=metric&APPID=****
 - meteo_qt
DEBUG: Fetching url for 6 days :http://api.openweathermap.org/data/2.5/forecast/daily?id=664460&mode=xml&units=metric&APPID=******
&cnt=7 - meteo_qt
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/meteo_qt/meteo_qt.py", line 763, in run
    timeout=5)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: <?xml version="1.0" encoding="UTF-8"?>
Aborted
`

**Comment by crismblog** [comment]
I deleted directory ~/.config/meteo-qt/ and restarted the application.
Now everything is going well.

**Comment by dglent** [comment]
I couldn't reproduce it either hear (with your city)
If it happens again, as first step you can open manually the url in the browser in order to see what the browser receives.
*i have to think to say to hide the personal key when i ask the logs .. hopefully you did it
